package-lock.json, package.json, server/db/db.js
=> update db name & project name from boilermaker to caaapstone

.gitignore, client/firebase.js, package-lock.json, package.json, server/api/users.js, server/firebase/firebaseDb.js, server/firebase/index.js, server/index.js
=> firebase synched

client/components/flights.js, client/components/index.js, client/routes.js, package-lock.json, package.json, public/index.html, public/style.css, server/api/destination.js, server/api/flights.js, server/api/index.js, server/db/models/destination.js, server/db/models/flight.js, server/db/models/trip.js, server/db/models/user.js, server/index.js
=> Flight search

server/api/trips.js, server/db/models/index.js, server/db/models/trip.js
also contains some of Collin's edits from the review
=> virtual method for trip array

client/components/flights.js, script/seed.js
=> Seed updates

client/components/mapBoard.js, client/store/maps.js, public/index.html
=> map do over, waiting for data

client/components/flights.js, client/store/trip.js
=> fetch trip issue fixed

client/components/main.js, client/components/userDashboard.js, client/routes.js, client/store/userTrips.js, package-lock.json, server/api/trips.js
=> progress on hooking things up

client/components/mapBoard.js, package-lock.json
=> remove this.map.remove()

client/components/JoinTrip.js, client/components/TripDetailsSetUp.js, client/components/userDashboard.js, client/routes.js, client/store/membership.js, client/store/userTrips.js, package-lock.json, package.json, server/api/memberships.js, server/db/models/membership.js
=> Create trip updates

client/components/flights.js, package-lock.json, package.json, public/style.css
=> flights page clean up

client/components/IdeaBoard.js, client/components/draggableActivity.js
=> FIXED (THANK YOU ALYSSA)

client/components/IdeaBoard.js, client/components/draggableActivity.js, client/components/index.js, client/components/main.js, client/store/users.js, server/api/users.js
Had to do with expecting different info to be on state.
=> finally fixed idea board bug

client/components/IdeaBoard.js
=> draggable card fix

client/components/IdeaBoard.js, client/components/calendarBoard.js, client/components/draggableActivity.js, public/style.css
Right now, it just changes the text color. I would love for it to be a border around the item instead, but couldn't make it work. We can come back to this and make any styling we choose conditional on how recently it was updated!
=> Activity changes color depending on how recently it was updated

client/components/userDashboard.js, public/style.css
=> user dashboard minor updates

.gitignore, firebase-key.json
=> more changes

client/components/flights.js, client/components/hotels.js, client/components/userDashboard.js, public/style.css, server/api/destination.js
=> flight and hotel updates/bug fixes

client/components/userDashboard.js
=> user dashboard updates

client/components/YelpPopUp.js, client/components/draggableYelpResult.js, client/components/index.js
=> yelp-popup

client/components/YelpPopUp.js, client/components/draggableYelpResult.js, client/components/index.js, client/components/main.js, client/store/trip.js, server/api/trips.js
=> Create firebase trip

client/components/TripDashboard.js, client/components/flights.js
=> navlink update

client/components/draggableYelpResult.js, client/components/mapBoard.js, client/store/maps.js
=> can get routes on a map

client/components/mapBoard.js, public/style.css
=> Landing page map

client/components/mapBoard.js
=> minor map changes

client/store/membership.js, server/api/memberships.js, server/api/trips.js
=> Wasn't able to figure out the Gravatars on the trip cards, but...added notes to routes, removed isUser from one route

client/components/Itinerary.js, client/components/mapBoard.js, public/style.css, server/api/flights.js, server/api/ideas.js
=> Itinerary experiment

client/components/auth-form.js, client/components/mapBoard.js, public/style.css
=> fix mapbox issue

client/components/JoinTrip.js, public/style.css
=> join trip updated

client/components/TripDetailsSetUp.js, public/style.css
=> Trip deatils cleanup

client/components/JoinTrip.js
=> join trip fix

client/components/calendarBoard.js
=> fixed isActive

server/db/models/trip.js
=> duration fixed

server/db/models/trip.js
=> dates fixed for shedule

client/components/Itinerary.js
=> date change

client/components/calendarBoard.js
=> ughhh again

client/components/Itinerary.js, client/components/userDashboard.js
=> Create trip fix

client/components/mapBoard.js
=> fix for map demo

client/components/mapBoard.js
=> fixed map for real

client/components/userDashboard.js
=> no nested p tags

client/components/TripDetailsSetUp.js
=> disable add friends

client/components/main.js, client/components/userDashboard.js
=> remove create a trip for demo

server/api/trips.js
=> image added to sample activity

client/components/TripDashboard.js
=> can now exit popup
